[CmdletBinding(SupportsShouldProcess)]
param(
    [Parameter(Mandatory = $true)]
    [ValidateScript({ Test-Path -LiteralPath $_ -PathType Container })]
    [string]$EditorModuleRoot,

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^[A-Za-z][A-Za-z0-9_]*$')]
    [string]$CommandletName,

    [Parameter(Mandatory = $true)]
    [switch]$ConfirmCleanup
)

$ErrorActionPreference = 'Stop'
if (-not $ConfirmCleanup) {
    throw 'ConfirmCleanup must be true before generated source is removed.'
}
$marker = 'Generated by dsh-UEAssetsOperator.'
$moduleRoot = [System.IO.Path]::GetFullPath($EditorModuleRoot)
$targets = @(
    [System.IO.Path]::GetFullPath((Join-Path $moduleRoot "Public\GeneratedCommandlets\$($CommandletName)Commandlet.h")),
    [System.IO.Path]::GetFullPath((Join-Path $moduleRoot "Private\GeneratedCommandlets\$($CommandletName)Commandlet.cpp"))
)
$rootPrefix = $moduleRoot.TrimEnd('\') + '\'
$removed = @()
$missing = @()

foreach ($target in $targets) {
    if (-not $target.StartsWith($rootPrefix, [System.StringComparison]::OrdinalIgnoreCase)) {
        throw "Resolved cleanup target escaped the Editor module root: $target"
    }
    if (-not (Test-Path -LiteralPath $target -PathType Leaf)) {
        $missing += $target
        continue
    }
    $firstLine = Get-Content -LiteralPath $target -TotalCount 1
    if ($firstLine -notlike "*$marker*") {
        throw "Refusing to remove an unmarked source file: $target"
    }
}

foreach ($target in $targets) {
    if (-not (Test-Path -LiteralPath $target -PathType Leaf)) {
        continue
    }
    if ($PSCmdlet.ShouldProcess($target, 'Remove generated Commandlet source')) {
        Remove-Item -LiteralPath $target
        $removed += $target
    }
}

foreach ($directory in ($targets | ForEach-Object { Split-Path -Parent $_ } | Select-Object -Unique)) {
    if ((Test-Path -LiteralPath $directory -PathType Container) -and
        -not (Get-ChildItem -LiteralPath $directory -Force | Select-Object -First 1)) {
        Remove-Item -LiteralPath $directory
    }
}

[ordered]@{
    success = $true
    removed = $removed
    already_missing = $missing
    requires_editor_rebuild = $true
    preserved = @('asset backups', 'validation reports', 'Unreal logs')
} | ConvertTo-Json -Depth 4
